# Generated by Django 4.2.16 on 2024-10-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, unique=True, verbose_name='facebook')),
                ('facebookAct', models.BooleanField(default=False, verbose_name='Facebook')),
                ('twitterAct', models.BooleanField(default=False, verbose_name='Twitter')),
                ('twitter', models.CharField(blank=True, default='/', max_length=100, verbose_name='Link')),
                ('instagramAct', models.BooleanField(default=False, verbose_name='Instagram')),
                ('instagram', models.CharField(blank=True, default='/', max_length=100, verbose_name='Link')),
                ('linkedinAct', models.BooleanField(default=False, verbose_name='Linkedin')),
                ('linkedin', models.CharField(blank=True, default='/', max_length=100, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='imagenes/avatars/')),
                ('cargo', models.CharField(max_length=200, verbose_name='cargo')),
                ('redes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='pass_app.redes')),
            ],
        ),
    ]
