# Generated by Django 4.2.16 on 2024-10-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0002_redes_miembro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='redes',
        ),
        migrations.AddField(
            model_name='miembro',
            name='facebook',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='facebookAct',
            field=models.BooleanField(default=False, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='instagram',
            field=models.CharField(blank=True, default='/', max_length=100, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='instagramAct',
            field=models.BooleanField(default=False, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='linkedin',
            field=models.CharField(blank=True, default='/', max_length=100, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='linkedinAct',
            field=models.BooleanField(default=False, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='twitter',
            field=models.CharField(blank=True, default='/', max_length=100, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='twitterAct',
            field=models.BooleanField(default=False, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='whatsapp'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='whatsappAct',
            field=models.BooleanField(default=False, verbose_name='Whatsapp'),
        ),
        migrations.DeleteModel(
            name='Redes',
        ),
    ]
