# Generated by Django 4.2.16 on 2024-10-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0003_remove_miembro_redes_miembro_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('ubicacion_mapa', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='miembro',
            name='facebook',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Link'),
        ),
    ]
